# to use this compose, you need run the "npm install" locally before run this
version: '2'
services:

  lb:
    image: dockercloud/haproxy
    links:
      - todo-frontend
      - static
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  static:
    build: ./nginx-static-files/
    ports:
      - 80
    volumes:
      - ./nginx-static-files/:/app/
      - ./nginx-static-files/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST=*/static/*

  dynamodb:
    image: dwmkerr/dynamodb
    command: -sharedDb
    ports:
      - "8000:8000"

  todo-backend:
    build: ./node-todo-backend/
    command: npm run dev
    volumes:
      - ./node-todo-backend/:/app/
    ports:
      - 3001:3001
    links:
      - dynamodb
    environment:
      - PORT=3001
      - AWS_ENDPOINT=dynamodb
      - AWS_REGION=localhost
      - AWS_ACCESS_KEY=abc
      - AWS_SECRET=def
      - ENVIRONMENT=DEV

  todo-frontend:
    build: ./node-todo-frontend/
    command: npm run dev
    volumes:
      - ./node-todo-frontend/:/app/
    ports:
      - 3000:3000
    links:
      - todo-backend
    environment:
      - TODO_BACKEND=todo-backend
      - TODO_BACKEND_PORT=3001
      - PORT=3000
      - VIRTUAL_HOST=*/todo/*


