version: '2'
services:

  lb:
    image: dockercloud/haproxy
    links:
      - todo-frontend
      - static
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  static:
    build: ./nginx-static-files/
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=*/static/*


  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  todo-backend:
    build: ./node-todo-backend/
    ports:
      - 3001
    links:
      - mongodb
    environment:
      - MONGODB=mongodb
      - MONGODB_PORT=27017
      - PORT=3001
    depends_on:
      - mongodb

  todo-frontend:
    build: ./node-todo-frontend/
    ports:
      - 3000
    links:
      - todo-backend
    environment:
      - TODO_BACKEND=todo-backend
      - TODO_BACKEND_PORT=3001
      - PORT=3000
      - VIRTUAL_HOST=*/todo/*


