version: '2'
services:

  lb:
    image: dockercloud/haproxy
    links:
      - todo-frontend
      - static
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  static:
    build: ./nginx-static-files/
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=*/static/*

  dynamodb:
    image: dwmkerr/dynamodb
    command: -sharedDb
    ports:
      - "8000:8000"

  todo-backend:
    build: ./node-todo-backend/
    ports:
      - 3001
    links:
      - dynamodb
    environment:
      - PORT=3001
      - AWS_ENDPOINT=dynamodb
      - AWS_REGION=localhost
      - AWS_ACCESS_KEY=abc
      - AWS_SECRET=def
      - ENVIRONMENT=DEV
    depends_on:
      - dynamodb

  todo-frontend:
    build: ./node-todo-frontend/
    ports:
      - 3000
    links:
      - todo-backend
    environment:
      - TODO_BACKEND=todo-backend
      - TODO_BACKEND_PORT=3001
      - PORT=3000
      - VIRTUAL_HOST=*/todo/*


