version: '2'
services:

  lb:
    image: dockercloud/haproxy
    links:
      - todo-frontend
      - todo-frontend2
      - static
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  static:
    image: nginx:latest
    ports:
      - 80
      - 8080:80
    volumes:
      - ./microservices-static-files-example/src/:/app/
      - ./microservices-static-files-example/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST=*/static/*


  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  todo-backend:
    image: node:latest
    #command: bash -c "cd /app/ && npm run compile && npm run dev"
    #command: bash -c "cd /app/ && npm run dev"
    command: bash -c "cd /app/ && npm run start"
    volumes:
      - "./microservices-node-example-todo-backend-mongodb/:/app/"
    ports:
      - 3001
    links:
      - mongodb
    environment:
      - MONGODB=mongodb
      - MONGODB_PORT=27017
      - PORT=3001

  todo-frontend:
    image: node:latest
    #command: bash -c "cd /app/ && npm run compile && npm run dev"
    command: bash -c "cd /app/ && npm run dev"
    #command: bash -c "cd /app/ && npm run start"
    volumes:
      - "./microservices-node-example-todo-frontend/:/app/"
    ports:
      - 3000
    links:
      - todo-backend
    environment:
      - TODO_BACKEND=todo-backend
      - TODO_BACKEND_PORT=3001
      - PORT=3000
      - VIRTUAL_HOST=*/todo/*

  todo-frontend2:
    image: node:latest
    #command: bash -c "cd /app/ && npm run compile && npm run dev"
    command: bash -c "cd /app/ && npm run dev"
    #command: bash -c "cd /app/ && npm run start"
    volumes:
      - "./microservices-node-example-todo-frontend2/:/app/"
    ports:
      - 3000
    links:
      - todo-backend
    environment:
      - TODO_BACKEND=todo-backend
      - TODO_BACKEND_PORT=3001
      - PORT=3000
      - VIRTUAL_HOST=*/todo/*

